# Generated by Django 5.2.1 on 2025-05-18 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=150, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Введите описание категории', null=True, verbose_name='Описание категории')),
                ('category_updated', models.DateTimeField(auto_now=True, verbose_name='Последняя модификация')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ваше имя и фамилию', max_length=50, verbose_name='Имя и Фамилия')),
                ('message', models.TextField(blank=True, help_text='Введите ваше сообщение', null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['name', 'message'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=150, verbose_name='Название продукта')),
                ('description', models.TextField(blank=True, help_text='Введите описание продукта', null=True, verbose_name='Описание продукта')),
                ('image', models.ImageField(blank=True, help_text='Загрузите фотографию продукта', null=True, upload_to='images/', verbose_name='Фотография')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Введите цену продукта', max_digits=100, verbose_name='Цена')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Введите дату создания', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Введите дату изменения', verbose_name='Дата изменения')),
                ('category', models.ForeignKey(blank=True, help_text='Введите название категории', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['name', 'description'],
            },
        ),
    ]
