# Generated by Django 5.2.1 on 2025-05-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_published_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_status',
            field=models.BooleanField(default=False, help_text='Товар в наличии'),
        ),
    ]
